openapi: 3.0.0
info:
  description: "An API for an envelope-based budgeting system. You can read more about the idea behind this here: [https://www.investopedia.com/envelope-budgeting-system-5208026](https://web.archive.org/web/20240124192318/https://www.investopedia.com/envelope-budgeting-system-5208026)"
  version: 0.0.1
  title: Envelope Budgeting
  termsOfService: http://TODO
  contact:
    email: mail@ratchek.com
  license:
    name: TODO
    url: http://TODO
externalDocs:
  description: Find out more about our budgeting API
  url: http://TODO
servers:
  - url: http://TODO
tags:
  - name: envelope
    description: Manage your envelopes
    externalDocs:
      description: TODO
      url: http://TODO
paths:
  /envelope:
    get:
      tags:
        - envelope
      summary: Get all the envelopes
      description: Returns an array of all the envelopes
      operationId: getListOfEnvelopeIds
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Envelope'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Envelope'
    post:
      tags:
        - envelope
      summary: Create a new envelope
      description: Creates a new envelope with the given name and amount
      operationId: createEnvelope
      requestBody:
        description: Envelope object that needs to be added to the system
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Envelope'
          application/xml:
            schema:
              $ref: '#/components/schemas/Envelope'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/Envelope'
        '400':
          description: Invalid envelope supplied

components:
  schemas:
    Envelope:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123456
        envelopeName:
          type: string
          example: utilities
        dollarsInEnvelope:
          type: integer
          format: int64
          example: 300
        centsInEnvelope:
          type: integer
          format: int32
          example: 15
