# Generated by Django 5.0.2 on 2024-03-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_envelope_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fill",
            name="envelope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fills",
                to="api.envelope",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="envelope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api.envelope",
            ),
        ),
    ]
