# Generated by Django 5.0.2 on 2024-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_fill_amount_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fill",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
